CREATE TABLE TB_EQUIPAMENTO (
                                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                NOME VARCHAR2(100) NOT NULL,
                                SETOR VARCHAR2(100) NOT NULL,
                                POTENCIA_WATTS NUMBER NOT NULL
);